Перечень научных профессиональных изданий Украины, в которых могут публиковаться результаты диссертационных работ на соискание научных степеней доктора и кандидата наук

По состоянию на 1 июня 2005 г.

ФІЗИКО-МАТЕМАТИЧНІ НАУКИ

* ЗБІРНИКИ НАУКОВИХ ПРАЦЬ

** Вісник Державного університету "Львівська політехніка" (математика, фізика приладів, елементів і систем, інформатика).
** Вісник Дніпропетровського державного університету.
** Вісник Донецького університету.
** Вісник Запорізького державного університету. Серія: фізико-математичні науки, біологічні науки (математичне моделювання та обчислювальні методи).
** Вісник Київського університету імені Тараса Шевченка. (Серії: фізико-математичні науки; математика і механіка).
** Вісник Львівського державного університету.
** Вісник Одеського державного університету (математика, механіка, фізика).
** Вісник Харківського університету. (Серія: математика, прикладна математика, механіка).
** Волинський математичний вісник (математика, інформатика).
** Динамические системы. (Сімферопольський державний універ­ситет).
** Збірник наукових праць Інституту математики НАН України. (Інститут математики НАН України) (математика).
** Науковий вісник Чернівецького державного університету (мате­матика, інформатика, фізика).
** Науковий часопис Національного педагогічного університету імені М.П. Драгоманова. Серія 1. Фізико-математичні науки, (фізика, математика).
** Наукові вісті Національного технічного університету України "КПІ", (математика).
** Наукові записки Національного педагогічного університету імені М.П. Драгоманова. Серія: фізико-математичні науки (математика).
** Обчислювальна та прикладна математика. (Київський націо­нальний університет ім. Тараса Шевченка) (математика, інформатика).
** Праці Інституту математики НАН України, (математика, інформатика).
** Теоретическая и прикладная механика. (Донецький державний університет) (математика, механіка).
** Труди Фізико-технічного інституту низьких температур ім. Б.І. Вєркіна НАН України (математика, фізика)
** Труды Института прикладной математики и механики (математика, механіка, інформатика).
** Ученые записки Симферопольского государственного универ­ситета (математика, фізика).

* ЖУРНАЛИ

** Алгебра та дискретна математика (Луганський державний педагогічний університет імені Тараса Шеченка МОН України), (алгебра та теорія чисел, математична логіка, теорія алгоритмів і дискретна математика).
 http://adm.luguniv.edu.ua/index.htm
Authors who wish to submit their papers should send paper in PDF format directly to anyone of the Editors or to the ADM primary address algebra@luguniv.edu.ua via electronic mail. E-mails of the Editors are listed on the Editorial Board page. The source TeX-file of the paper will be needed if it accepted for publication.

**  Доповіді НАН України.
** Журнал обчислювальної та прикладної математики (Київський університет імені Тараса Шевченка, мале підприємство "ТВ і МС"), (математика, інформатика).
** Київський національний університет імені Тараса Шевченка, факультет кібернетики, кафедра обчислювальної математики
просп. академіка Глушкова, 2, корп. 6, Київ, Україна, 03022
Тел.: (0482) 259-0889
E-mail: sil@dialektika.com, vm214@dcp.kiev.ua

** Кибернетика и системный анализ. (Інститут кібернетики ім. В.М. Глушкова НАН України) (інформатика, обчислювальна математика, варіаційне числення та теорія оптимального керування, дослідження операцій та теорія ігор).
** Математическая физика, анализ, геометрия. (Фізико-технічний інститут низьких температур ім. Б.І. Вєркіна НАН України) (математика)
** Математичні методи та фізико-механічні поля. (Фізико-механічний інститут ім. Г.В. Карпенка НАН України) (математика, механіка, інфор­матика).
** Математичні студії. (Львівський національний університет ім. Івана Франка) (математика).
** Меthods of Functional Analysis and Topology. (Інститут математики НАН України) (математика).
** Науковий вісник Ужгородського університету. Серія: математика (алгебра та теорія чисел).
** Науковий вісник Ужгородського університету. Серія: математика і інформатика (алгебра та теорія чисел, інформатика).
** Теория случайных процессов. (Інститут прикладної математики і механіки НАН України) (математика).
** Теорія ймовірностей та математична статистика. (Київський націо­наль­ний університет ім. Тараса Шевченка) (математика).
** Український математичний вісник (Луганський державний педагогічний університет імені Тараса Шевченка), (математика, теоретична механіка).
Інструкції для авторів

Статті, що подаються до розгляду в журнал «Український математичний вісник» (УМВ), повинні бути написані українською, російською або англійською мовою та підготовлені за допомогою комп'ютера.
Підготовка на комп'ютері має бути виконана у форматах AMS-LATEX, LATEX або LATEX2е. Малюнки повинні бути представлені в окремому файлі в одному з наступних форматів РS, ВМР, РСХ, ТІFF, JРЕG з розрішуючою можливістю не менше ніж 600 dpі. До кожної статті необхідно додати наступну інформацію: повні поштові адреси всіх авторів; електронні адреси авторів; анотації статей; індекс предметної класифікації МSС 2000; ключові слова та фрази.
Редакція рекомендує надсилати електронний варіант статті в форматі РоstSсrірt або РGF за адресою:
UMB. Submission@iamm.ac.donetsk.ua

Надрукована на принтері стаття у двох примірниках має бути надіслана за адресою:
Редакція УМВ Інститут прикладної математики і механіки
Національної академії наук України, вул. Р. Люксембург, 74,
83114, Донецьк, УКРАЇНА.

Більш детально дізнатися про оформлення статей та отримати зразок оформлення можна на сайті http://www.iamm.ac.donetsk.ua/umb/ 

** Учёные записки Таврического университета им. В.И.Вернадского (математика, фізика).


